# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BsuirSchedule < Formula
  desc ""
  homepage ""
  version "0.0.1-prerelease"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/moonkracker/bsuir-schedule/releases/download/v0.0.1-prerelease/bsuir-schedule_0.0.1-prerelease_darwin_arm64.tar.gz"
      sha256 "5e48aa3502ae35cb2314fac90b276b0393f3d83a6f24a47213cdde51d24c9374"

      def install
        bin.install "bsuir-schedule"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moonkracker/bsuir-schedule/releases/download/v0.0.1-prerelease/bsuir-schedule_0.0.1-prerelease_darwin_amd64.tar.gz"
      sha256 "536147f18b10595ec55400ed0ed7d38fcef8711e7e8dba29a74d2b1e16560e80"

      def install
        bin.install "bsuir-schedule"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonkracker/bsuir-schedule/releases/download/v0.0.1-prerelease/bsuir-schedule_0.0.1-prerelease_linux_arm64.tar.gz"
      sha256 "cd3b2ae7b57cbc5631fb1787a87dfc66484442743a5fdd76fa6fef98f6f7528a"

      def install
        bin.install "bsuir-schedule"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moonkracker/bsuir-schedule/releases/download/v0.0.1-prerelease/bsuir-schedule_0.0.1-prerelease_linux_amd64.tar.gz"
      sha256 "3ec6db4bb5ee3091ff8817a7776d5b2d89495572e93c2d8dd89fedd281fb93e7"

      def install
        bin.install "bsuir-schedule"
      end
    end
  end
end
