# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BsuirSchedule < Formula
  desc "Get BSUIR schedule"
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/moonkracker/bsuir-schedule/releases/download/v0.0.2/bsuir-schedule_0.0.2_darwin_arm64.tar.gz"
      sha256 "f23877b6831433000e4d6a4231a881b22e2ef2415b0fe91b8f4949ad1c5d5e09"

      def install
        bin.install "bsuir-schedule"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moonkracker/bsuir-schedule/releases/download/v0.0.2/bsuir-schedule_0.0.2_darwin_amd64.tar.gz"
      sha256 "7356c921d371b267019805e03b4a48c3cb099c6b22ae36cc3a4a966d22591df7"

      def install
        bin.install "bsuir-schedule"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moonkracker/bsuir-schedule/releases/download/v0.0.2/bsuir-schedule_0.0.2_linux_arm64.tar.gz"
      sha256 "ac2429612f76a73146bfbf9df5da52100af28d385a04db1ef2d1ce845bb2fc74"

      def install
        bin.install "bsuir-schedule"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moonkracker/bsuir-schedule/releases/download/v0.0.2/bsuir-schedule_0.0.2_linux_amd64.tar.gz"
      sha256 "754cc50dd8c1728d957b0655ed72035d2460884749dd95e82cd5530679f9f05e"

      def install
        bin.install "bsuir-schedule"
      end
    end
  end
end
